// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "AutonomousCommand.h"
#include "../Commands/RON.h"
#include "../Commands/ROFF.h"
#include "../Commands/WON.h"
#include "../Commands/WOFF.h"
#include "../Commands/BON.h"
#include "../Commands/BOFF.h"

AutonomousCommand::AutonomousCommand() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
//	Requires(Robot::lights);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void AutonomousCommand::Initialize() {
	timer.Reset();
	timer.Start();
	
	
}
// Called repeatedly when this Command is scheduled to run
void AutonomousCommand::Execute() {
	time = timer.Get();
	if(time < 1)
		(new RON())->Start();
	
	if((time > 1) && (time < 2) )
		(new ROFF())->Start();
	
	if((time > 1.05) && (time < 2) )
		(new WON ())->Start();
	
	if((time > 2) && (time < 3) )
		(new WOFF ())->Start();
	
	if((time > 2.05) && (time < 3) )
		(new BON ())->Start();
	
	if((time > 3.05) && (time < 4) )
		(new BOFF ())->Start();
}
// Make this return true when this Command no longer needs to run execute()
bool AutonomousCommand::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void AutonomousCommand::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonomousCommand::Interrupted() {
}
