// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RON.h"
RON::RON() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::lights);
	printf("hellol!!");
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void RON::Initialize() {
	RobotMap::lightsRedspike->Set(Relay::kForward);
	printf("intialize");
}
// Called repeatedly when this Command is scheduled to run
void RON::Execute() {
	printf("execute");
}
// Make this return true when this Command no longer needs to run execute()
bool RON::IsFinished() {
	
	return false;
	printf("is finsihed");
	
}
// Called once after isFinished returns true
void RON::End() {
	printf("ending");
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void RON::Interrupted() {
	printf("ohhp u got interrupted"); 
}
